#!/usr/bin/env sh
set -eux

BUILD_PACKAGES_DEPENDENCIES=curl
apk add --no-cache ${BUILD_PACKAGES_DEPENDENCIES}

curl -SL --output phpPgAdmin.zip https://github.com/phppgadmin/phppgadmin/releases/download/REL_7-12-1/phpPgAdmin-7.12.1.zip
unzip phpPgAdmin.zip
mv ./phpPgAdmin-7.12.1/* ${DOCKAGE_WEBROOT_DIR}
mv ${DOCKAGE_WEBROOT_DIR}/conf/config.inc.php-dist ${DOCKAGE_WEBROOT_DIR}/conf/config.inc.php
chown -R nginx:nginx ${DOCKAGE_WEBROOT_DIR}

rm -rf phpPgAdmin.zip phpPgAdmin-7.12.1
apk del ${BUILD_PACKAGES_DEPENDENCIES}